"""add document status_detail and progress

Revision ID: 6a4c95600e4d
Revises: 3e24525b95ec
Create Date: 2026-02-19 08:11:36.647790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6a4c95600e4d'
down_revision: Union[str, Sequence[str], None] = '3e24525b95ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('status_detail', sa.String(length=500), nullable=True))
    op.add_column('documents', sa.Column('ocr_progress', sa.Integer(), nullable=True))
    op.alter_column('documents', 'ocr_status',
               existing_type=postgresql.ENUM('pending', 'processing', 'complete', 'failed', name='ocr_status_enum'),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::ocr_status_enum"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'ocr_status',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('pending', 'processing', 'complete', 'failed', name='ocr_status_enum'),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::ocr_status_enum"))
    op.drop_column('documents', 'ocr_progress')
    op.drop_column('documents', 'status_detail')
    # ### end Alembic commands ###
